const AppState = {
  INTRO: "intro", WELCOME: "welcome", WHAT_IS: "what-is", ADA_DESIGN: "ada-design",
  PRIVACY_WHY: "privacy-why", PRIVACY_VIEW: "privacy-view", ARTIFACT: "artifact",
  CARE_SIGNALS: "care-signals", AGREEMENT: "agreement", AGREEMENT_COMPLETE: "agreement-complete",
  ADD_CHILD: "add-child", PRIMARY_PROFILE: "primary-profile", STUDENT_INVITE: "student-invite",
  FAMILY_DASHBOARD_INTRO: "family-dashboard-intro", FAMILY_DASHBOARD_MISSIONS: "family-dashboard-missions", FAMILY_DASHBOARD_DEPTH: "family-dashboard-depth", FAMILY_SUMMARY: "family-summary", STUDENT_ENTRY: "student-entry", STUDENT_WELCOME: "student-welcome",
  STUDENT_PRIVACY: "student-privacy", STUDENT_AGREEMENT: "student-agreement", STUDENT_PROFILE: "student-profile",
  STUDENT_MISSION: "student-mission", STUDENT_ARTIFACT: "student-artifact", STUDENT_READY: "student-ready"
};

const onboardingData = { childName: "", stage: "", grade: "", avatar: "", inviteMethod: "link", agreementAccepted: false, selectedArtifactAge: "primary", studentName: "", studentInterests: [], studentAgreementAccepted: false, reportStudent: "leo", reportVisual: "climate" };
const ASSETS = {
  logo: "assets/digizen-logo.svg", adaFull: "assets/shared/ADA-full-body.png", adaProfile: "assets/shared/ada-profile-low.png",
  agreement: "generated-assets/digizen-acuerdo-pinky-promise-gpt-image-2-v01.png",
  avatars: ["generated-assets/digizen-preset-avatar-set-mx-v02-01.png", "generated-assets/digizen-preset-avatar-set-mx-v02-02.png", "generated-assets/digizen-preset-avatar-set-mx-v02-03.png", "generated-assets/digizen-preset-avatar-set-mx-v02-04.png", "generated-assets/digizen-preset-avatar-set-mx-v02-05.png", "generated-assets/digizen-preset-avatar-set-mx-v02-06.png"]
};
const familyReportData = {
  leo: { name: "Leo", level: "5.º primaria", role: "Testigo / Guía", topic: "Privacidad y seguridad", climate: "Refugio Seguro", node: "Protección de Privacidad", icon: "🛡️", mapKey: "privacy", context: "Tu hijo está fortaleciendo sus defensas digitales. Hoy analizó con ADA por qué compartir contraseñas o datos personales en chats de videojuegos puede convertirse en una trampa, aunque parezca inofensivo.", artifact: "Le dije a ADA que si un jugador en Roblox me pide mi correo o me promete Robux gratis a cambio de mi clave, debo decirle que NO y contárselo a mis papás de inmediato porque puede ser una trampa.", question: "Oye, vi que hoy estuviste revisando con ADA el tema de las trampas en los juegos en línea. ¿Alguna vez alguien te ha ofrecido regalos raros en un chat?", situation: "Me dio mucho orgullo saber que tienes claro que tu contraseña es secreta, como la llave de nuestra casa.", close: "Si algún día ves algo en un juego que te dé duda o susto, acuérdate que puedes venir a decirme sin que me enoje contigo.", challengeTitle: "Cazadores de Llaves Secretas", challengeSteps: ["Revisen juntos las configuraciones de seguridad del juego favorito de Leo.", "Verifiquen que el perfil esté en ‘Privado’ y que el chat de voz solo esté activo para amigos conocidos de la escuela.", "Inventen una frase clave familiar de emergencia para situaciones raras."], challengeGoal: "Convertir la privacidad en una dinámica de equipo donde Leo siente que el adulto es su aliado de juego, no su vigilante.", theoryTitle: "Huella digital pasiva en la infancia", theoryText: "En primaria alta, las cuentas de juego o video guardan información de su comportamiento. Aprender a cerrar sesión y proteger su clave ayuda a prevenir exposición a contactos no deseados y extracción comercial de datos." },
  sofia: { name: "Sofía", level: "1.º secundaria", role: "Observador / Facilitador", topic: "Identidad y filtros", climate: "Terreno Fértil", node: "Identidad Positiva", icon: "🌱", mapKey: "identity", context: "Tu hija está construyendo su identidad digital con autenticidad. Hoy analizó el impacto de los filtros y las métricas en redes sociales para cuestionar la presión de la validación externa.", artifact: "Quiero que mis historias muestren algo que realmente elegí. Puedo usar filtros por diversión, pero no quiero sentir que necesito cambiar toda mi cara para recibir likes.", question: "He notado que los filtros de ahora cambian muchísimo las caras, ¿tú crees que usar filtros es solo por diversión o a veces la gente los usa por presión?", situation: "Me pareció genial tu regla de dejar publicada tu historia mostrando tus outfits sin revisar las vistas por media hora. ¿Cómo crees que te sentirás al no estar pendiente del celular de inmediato?", close: "Me da mucho orgullo que decidas que tu valor como creadora no depende de un número de visualizaciones.", challengeTitle: "Auditoría de Vitrinas", challengeSteps: ["Abran juntos el feed de Instagram o TikTok, puede ser el tuyo o el de Sofía.", "Durante dos minutos clasifiquen las primeras 10 publicaciones: ‘Momento real’ o ‘Performance / vitrina’.", "Pregúntale: ‘¿Qué crees que intenta demostrar esta persona con esta foto?’"], challengeGoal: "Reírse juntos de lo irreales que pueden ser los algoritmos, validando que Sofía ya sabe detectar esos trucos.", theoryTitle: "Performance digital", theoryText: "Ocurre cuando los adolescentes editan su identidad para encajar en estándares que los algoritmos premian con likes y visibilidad. En vez de juzgar, valida la presión y recuerda que su valor no se mide en métricas." },
  mateo: { name: "Mateo", level: "2.º preparatoria", role: "Par / Socio estratégico", topic: "Sistemas IA (ATS)", climate: "Faro del Criterio", node: "Análisis Crítico de Sistemas", icon: "🔎", mapKey: "algorithmic", context: "Tu hijo está desarrollando análisis crítico de sistemas de IA. Hoy cuestionó cómo los sistemas de selección automatizada filtran currículums y aprendió a detectar sesgos sin dejarse manipular por métricas vacías.", artifact: "Me di cuenta de que un ATS puede descartar mi currículum por el formato o por no repetir ciertas palabras clave. Voy a estructurar mi información pensando en cómo la lee un sistema, sin perder mi voz real.", question: "Qué interesante lo que viste hoy sobre los sistemas que filtran currículums antes que una persona. ¿Te sorprendió que una máquina decida eso primero?", situation: "Me gusta mucho que estés pensando en cómo comunicarte tanto con personas como con sistemas automatizados — es una habilidad que te va a servir toda la vida.", close: "Es impresionante cómo la Inteligencia Artificial nos obliga a todos a ser más estratégicos y honestos con lo que compartimos.", challengeTitle: "Audita tu propio perfil", challengeSteps: ["Elijan juntos una vacante real que le interese a Mateo.", "Identifiquen cinco palabras clave que el anuncio repite y que un sistema ATS probablemente busca.", "Compárenlas con un borrador de su currículum o perfil, sin inventar experiencia falsa."], challengeGoal: "Tratar a Mateo como un ciudadano digital adulto en formación, validando su criterio y su preparación real para el mundo laboral.", theoryTitle: "Sesgo algorítmico en sistemas de selección (ATS)", theoryText: "Los jóvenes empiezan a interactuar con sistemas que toman decisiones sobre ellos sin supervisión humana directa. Entender sus filtros, límites y sesgos desarrolla pensamiento estratégico sin caer en cinismo ni en manipulación." }
};
// Valores internos de cobertura por habilidad, en el orden fijo de la malla.
// Se visualizan sin cifras para evitar convertir el reporte en una evaluación.
const familyReportCoverage = {
  leo: { values: [90, 55, 60, 60, 65, 50, 45, 40, 50, 88, 35], featured: ["privacy", "data"] },
  sofia: { values: [60, 90, 65, 55, 60, 45, 50, 42, 55, 48, 85], featured: ["identity", "authorship"] },
  mateo: { values: [55, 60, 70, 55, 60, 40, 45, 42, 92, 50, 38], featured: ["critical", "algorithmic"] }
};
const reportAvatars = { leo: ASSETS.avatars[0], sofia: ASSETS.avatars[1], mateo: ASSETS.avatars[2] };
const secondaryWeeklyMissions = {
  leo: { title: "Compartir no es regalar datos", topic: "Privacidad en juegos", skill: "Protección de datos", icon: "🔐", context: "Leo distinguió entre compartir una jugada y entregar información que una persona desconocida podría usar fuera del juego.", artifact: "Antes de responder en un chat, puedo preguntarme si lo que me piden es algo que también le diría a alguien que no conozco.", question: "Cuando alguien te escribe en un juego, ¿cómo decides qué sí puedes contarle?", situation: "Me gusta que puedas divertirte y al mismo tiempo cuidar lo que es tuyo.", close: "Si no estás seguro, parar y preguntar siempre es una buena decisión.", challengeTitle: "El semáforo del chat", challengeSteps: ["Elijan tres mensajes ficticios de un chat de juego.", "Clasifíquenlos en verde, amarillo o rojo según la información que piden.", "Inventen una respuesta segura para uno de los mensajes amarillos."], challengeGoal: "Practicar una pausa sencilla antes de compartir datos personales.", theoryTitle: "Decisiones pequeñas, protección real", theoryText: "La privacidad infantil se construye con decisiones cotidianas y lenguaje concreto. El objetivo no es generar miedo, sino normalizar que pedir ayuda también es una habilidad digital." },
  sofia: { title: "Lo que un filtro no cuenta", topic: "Identidad digital", skill: "Autoría creativa", icon: "🎨", context: "Sofía revisó cómo una imagen editada puede comunicar estilo sin tener que definir su valor o su identidad frente a otras personas.", artifact: "Puedo usar un filtro porque me gusta, no porque siento que sin él no puedo mostrarme.", question: "¿Qué cambia entre usar un filtro para jugar y usarlo para sentir que una foto vale más?", situation: "Me gusta que puedas decidir cómo expresarte sin que un algoritmo lo decida por ti.", close: "Tu mirada y tus decisiones valen más que una métrica.", challengeTitle: "Dos versiones, una misma persona", challengeSteps: ["Elijan una imagen editada y una imagen cotidiana.", "Conversen sobre qué comunica cada una sin juzgar cuál es mejor.", "Nombren una cosa real que les guste de cada imagen."], challengeGoal: "Abrir una conversación sobre expresión y presión sin convertirla en interrogatorio.", theoryTitle: "Identidad y contexto", theoryText: "Los adolescentes exploran identidad mediante imágenes, audiencias y pertenencia. El acompañamiento útil no prohíbe la expresión: ayuda a reconocer cuándo una plataforma transforma una elección en presión." },
  mateo: { title: "Lo que una plataforma deduce", topic: "Sistemas algorítmicos", skill: "Análisis crítico de sistemas", icon: "🔎", context: "Mateo identificó que una plataforma puede inferir intereses y prioridades a partir de señales mínimas, aunque nunca explique del todo cómo llega a ellas.", artifact: "Si una plataforma me recomienda algo, puedo preguntarme qué datos o decisiones pudieron hacer que apareciera frente a mí.", question: "¿Qué crees que una plataforma puede asumir de ti solo por cómo la usas?", situation: "Cuestionar un sistema no significa dejar de usarlo: significa usarlo con más criterio.", close: "Tú puedes decidir qué tanto dejas que una recomendación influya en tus siguientes pasos.", challengeTitle: "Rastrea una recomendación", challengeSteps: ["Elijan una recomendación reciente de una plataforma.", "Anoten tres señales que pudieron influir en que apareciera.", "Piensen qué información falta para saber si esa recomendación realmente conviene."], challengeGoal: "Convertir una recomendación cotidiana en una conversación sobre criterio y autonomía.", theoryTitle: "Inferencias automatizadas", theoryText: "Los sistemas de recomendación elaboran perfiles probabilísticos a partir de comportamiento, contexto y datos de otras personas. Entender la inferencia ayuda a tomar distancia sin asumir que toda automatización es neutral." }
};
const abrirGuides = {
  "leo-01": { opener: "Hoy me llegó un correo del trabajo que parecía una oportunidad, pero antes de explicar bien ya me estaba pidiendo datos. Me hizo desconfiar.", relate: "A mí también me cuesta saber cuándo una oferta es amable y cuándo está diseñada para que alguien entregue algo importante.", invite: "¿Tú cómo ves que alguien pida una clave a cambio de algo que parece gratis?", reflect: "Tiene sentido que las ofertas rápidas puedan hacer difícil pensar con calma.", exit: "Gracias, me interesaba saber cómo lo ves. Si otro día sale el tema, seguimos." },
  "leo-02": { opener: "Una amiga me contó que aceptó una invitación en una app y luego se dio cuenta de que había compartido más de lo que pensaba.", relate: "Yo también tengo que revisar qué comparto; no siempre es obvio dónde está el límite.", invite: "¿Para ti qué información debería quedarse fuera de un chat de juego?", reflect: "Suena a que para ti importa distinguir entre convivir y regalar algo privado.", exit: "Gracias por pensarlo conmigo. No hace falta resolverlo todo hoy." },
  "sofia-01": { opener: "En redes vi una foto de una conocida que se veía tan perfecta que me hizo dudar de cuánto era una foto y cuánto era edición.", relate: "A veces olvido que una imagen puede mostrar estilo sin contar toda la historia de una persona.", invite: "¿Para ti cuándo un filtro es juego y cuándo empieza a poner presión?", reflect: "Entiendo: usar algo por gusto no es lo mismo que sentir que sin eso no puedes aparecer.", exit: "Me gustó escuchar cómo lo ves. Si quieres, otro día volvemos al tema." },
  "sofia-02": { opener: "A veces antes de subir una foto me descubro pensando más en cómo se va a ver que en si realmente quiero compartirla.", relate: "Yo también edito lo que muestro; a veces no sé si es por estilo o por querer encajar.", invite: "¿Qué crees que cambia cuando una imagen se comparte para expresarse y no para recibir aprobación?", reflect: "Tiene sentido que la intención cambie por completo cómo se siente compartirla.", exit: "Gracias por tu perspectiva. No necesitamos llegar a una regla hoy." },
  "mateo-01": { opener: "En el trabajo vi cómo un sistema filtra solicitudes antes de que una persona las revise. Me hizo pensar en cuántas decisiones pasan así todos los días.", relate: "Me parece útil entender esos filtros, aunque tampoco creo que debamos convertirnos en lo que el sistema espera.", invite: "¿Qué te parece justo o injusto de que un sistema revise un currículum antes que alguien?", reflect: "Entiendo que conocer el sistema puede servir sin tener que renunciar a tu propia voz.", exit: "Gracias por pensarlo conmigo. Si te interesa, luego revisamos un ejemplo real." },
  "mateo-02": { opener: "Un amigo me recomendó una compra porque le apareció muchas veces en redes; me pregunté qué tuvo que pasar para que la plataforma insistiera tanto.", relate: "A mí me ayuda preguntarme qué señales pudo haber usado una plataforma antes de tomarla como buena idea.", invite: "¿Qué datos crees que una plataforma usa para asumir qué te interesa?", reflect: "Sí, cuestionar una recomendación no es dejar de usarla; es recuperar parte de la decisión.", exit: "Me interesaba conocer tu lectura. Lo dejamos aquí si prefieres." }
};
const missionBriefs = {
  "leo-01": "Reconocer cuándo una oferta digital puede pedir más de lo que parece.",
  "leo-02": "Distinguir entre participar en un chat y compartir datos privados.",
  "sofia-01": "Pensar cómo los filtros cambian la forma en que nos mostramos.",
  "sofia-02": "Separar la expresión personal de la presión por aprobación.",
  "mateo-01": "Cuestionar cómo un sistema automatizado toma decisiones sobre personas.",
  "mateo-02": "Entender qué señales pueden alimentar una recomendación digital."
};
const dashboardMetricSets = {
  climate: [["privacy", "🛡️", "Refugio Seguro", "Protección de Privacidad"], ["identity", "🌱", "Terreno Fértil", "Identidad Positiva"], ["critical", "☀️", "Visión Despejada", "Pensamiento Crítico"], ["community", "🌊", "Corrientes de Empatía", "Empatía y Liderazgo"], ["wellbeing", "⚖️", "Ecosistema en Equilibrio", "Autorregulación Digital"], ["technology", "⛰️", "Cumbres de Innovación", "Comprensión Tecnológica"]],
  skills: [["ethics", "🧭", "Aurora Ética", "Ética en IA"], ["justice", "🌉", "Puentes de Justicia", "Inclusión Digital"], ["algorithmic", "🔎", "Faro del Criterio", "Análisis Crítico de Sistemas"], ["data", "🔐", "Atmósfera Blindada", "Privacidad de Datos"], ["authorship", "🎨", "Manantial Creativo", "Autoría Creativa"]]
};
const primarySkillMetric = { leo: "data", sofia: "authorship", mateo: "algorithmic" };
function activeDashboardMetric(studentKey, report, visual = onboardingData.reportVisual) {
  const set = visual === "climate" ? dashboardMetricSets.climate : dashboardMetricSets.skills;
  const key = visual === "climate" ? report.mapKey : primarySkillMetric[studentKey];
  return set.find(([metricKey]) => metricKey === key) || set[0];
}
const JOIN_URL = "https://digizen.app/join/DGZ-7K29A";
// Mantiene el punto de conexión original: si se agrega un saludo en video,
// ADA usa ese medio; mientras tanto siempre se muestra el PNG local.
const ADA_VIDEO = { src: "", poster: ASSETS.adaFull };
const HOLD_DURATION = 2000;
const INTRO_DURATION = 2600;
const screen = document.querySelector("#screen");
const transitionVeil = document.querySelector("#transitionVeil");
const progressText = document.querySelector("#progressText");
const progressDots = document.querySelector("#progressDots");
const liveRegion = document.querySelector("#liveRegion");
const reviewMenu = document.querySelector("#reviewMenu");
const reviewMenuToggle = document.querySelector("#reviewMenuToggle");
let currentState = AppState.INTRO;
let introTimer = 0, holdFrame = 0, holdStart = 0, holdProgress = 0, holdLocked = false, editingChild = false;

function escapeHtml(value) { return String(value).replace(/[&<>"']/g, char => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" }[char])); }
function announce(message) { liveRegion.textContent = ""; requestAnimationFrame(() => { liveRegion.textContent = message; }); }
function stageLabel() { return ({ primary: "primaria alta", middle: "secundaria", high: "preparatoria" })[onboardingData.stage] || ""; }
function gradeLabel() { return onboardingData.grade ? `${onboardingData.grade} de ${stageLabel()}` : ""; }
function selectedAvatar() { return onboardingData.avatar || ASSETS.avatars[0]; }
function isStudentState(state) { return state.startsWith("student-"); }
function studentStageLabel() { return ({ primary: "4.º, 5.º o 6.º de primaria", middle: "Secundaria", high: "Preparatoria" })[onboardingData.stage] || "Secundaria"; }

function progressIndex(state) {
  return ({ [AppState.INTRO]: 0, [AppState.WELCOME]: 1, [AppState.WHAT_IS]: 2, [AppState.ADA_DESIGN]: 3, [AppState.PRIVACY_WHY]: 4, [AppState.PRIVACY_VIEW]: 5, [AppState.ARTIFACT]: 6, [AppState.CARE_SIGNALS]: 7, [AppState.AGREEMENT]: 8, [AppState.AGREEMENT_COMPLETE]: 8, [AppState.ADD_CHILD]: 9, [AppState.PRIMARY_PROFILE]: 10, [AppState.STUDENT_INVITE]: 10, [AppState.FAMILY_DASHBOARD_INTRO]: 11, [AppState.FAMILY_DASHBOARD_MISSIONS]: 11, [AppState.FAMILY_DASHBOARD_DEPTH]: 11, [AppState.FAMILY_SUMMARY]: 11 })[state] || 1;
}
function renderProgress(state) {
  const current = progressIndex(state);
  const studentSteps = { [AppState.STUDENT_ENTRY]: 1, [AppState.STUDENT_WELCOME]: 2, [AppState.STUDENT_PRIVACY]: 3, [AppState.STUDENT_AGREEMENT]: 4, [AppState.STUDENT_PROFILE]: 5, [AppState.STUDENT_MISSION]: 6, [AppState.STUDENT_ARTIFACT]: 7, [AppState.STUDENT_READY]: 7 };
  const total = isStudentState(state) ? 7 : 11;
  const position = isStudentState(state) ? studentSteps[state] : current;
  progressText.textContent = state === AppState.INTRO ? "" : state === AppState.FAMILY_SUMMARY ? "Panel familiar" : state === AppState.STUDENT_READY ? "Listo" : isStudentState(state) ? `Tu acceso · ${position} de ${total}` : `${position} de ${total}`;
  progressDots.innerHTML = Array.from({ length: total }, (_, index) => `<span class="progress-dot ${index + 1 <= position ? "is-active" : ""}"></span>`).join("");
}
function transitionTo(nextState) {
  if (nextState === currentState && screen.innerHTML) return;
  clearTimeout(introTimer); transitionVeil.classList.remove("is-opening"); transitionVeil.classList.add("is-closing"); screen.classList.remove("is-entering"); screen.classList.add("is-leaving");
  setTimeout(() => { currentState = nextState; render(); screen.classList.remove("is-leaving"); screen.classList.add("is-entering"); transitionVeil.classList.remove("is-closing"); transitionVeil.classList.add("is-opening"); setTimeout(() => transitionVeil.classList.remove("is-opening"), 720); }, 380);
}

function reviewMenuGroup(title, items) {
  return `<section><h3>${title}</h3>${items.map(([state, label]) => `<button type="button" data-review-state="${state}">${label}</button>`).join("")}</section>`;
}

function setupReviewMenu() {
  document.querySelector("#reviewMenuParent").innerHTML = reviewMenuGroup("Onboarding familiar", [[AppState.WELCOME, "P1 · Bienvenida ADA"], [AppState.WHAT_IS, "P2 · Qué es DIGIZEN"], [AppState.ADA_DESIGN, "P3 · Diseño de ADA"], [AppState.PRIVACY_WHY, "P4 · Privacidad"], [AppState.PRIVACY_VIEW, "P5 · Qué verá la familia"], [AppState.ARTIFACT, "P6 · Artefacto"], [AppState.CARE_SIGNALS, "P7 · Señales de cuidado"], [AppState.AGREEMENT, "P8 · Acuerdo"], [AppState.ADD_CHILD, "P9 · Agregar alumno"], [AppState.PRIMARY_PROFILE, "P10A · Primaria alta"], [AppState.STUDENT_INVITE, "P10B · Invitación"], [AppState.FAMILY_DASHBOARD_INTRO, "P11A · Panorama semanal"], [AppState.FAMILY_DASHBOARD_MISSIONS, "P11B · Misiones"], [AppState.FAMILY_DASHBOARD_DEPTH, "P11C · Profundidad opcional"]]);
  document.querySelector("#reviewMenuStudent").innerHTML = reviewMenuGroup("Onboarding de alumno", [[AppState.STUDENT_ENTRY, "A0 · Entrada"], [AppState.STUDENT_WELCOME, "A1 · ADA por edad"], [AppState.STUDENT_PRIVACY, "A2 · Privacidad"], [AppState.STUDENT_AGREEMENT, "A2B · Acuerdo"], [AppState.STUDENT_PROFILE, "A3 · Nombre e intereses"], [AppState.STUDENT_MISSION, "A4 · Misión"], [AppState.STUDENT_ARTIFACT, "A5 · Artefacto"], [AppState.STUDENT_READY, "Final · Primera misión"]]);
  document.querySelector("#reviewMenuReport").innerHTML = reviewMenuGroup("Reporte", [[AppState.FAMILY_SUMMARY, "Dashboard · Resumen familiar"]]);
  reviewMenuToggle.addEventListener("click", () => {
    const open = reviewMenuToggle.getAttribute("aria-expanded") === "true";
    reviewMenuToggle.setAttribute("aria-expanded", String(!open));
    reviewMenu.hidden = open;
  });
  reviewMenu.addEventListener("click", event => {
    const target = event.target.closest("[data-review-state]");
    if (!target) return;
    reviewMenu.hidden = true;
    reviewMenuToggle.setAttribute("aria-expanded", "false");
    transitionTo(target.dataset.reviewState);
  });
}
function render() {
  document.querySelector(".app-shell").classList.toggle("is-intro", currentState === AppState.INTRO); renderProgress(currentState);
  screen.classList.toggle("is-dashboard", currentState === AppState.FAMILY_SUMMARY);
  const views = {
    [AppState.INTRO]: renderIntro, [AppState.WELCOME]: renderWelcome, [AppState.WHAT_IS]: renderWhatIs, [AppState.ADA_DESIGN]: renderAdaDesign, [AppState.PRIVACY_WHY]: renderPrivacyWhy, [AppState.PRIVACY_VIEW]: renderPrivacyView, [AppState.ARTIFACT]: renderArtifact, [AppState.CARE_SIGNALS]: renderCareSignals, [AppState.AGREEMENT]: renderAgreement, [AppState.AGREEMENT_COMPLETE]: renderAgreementComplete, [AppState.ADD_CHILD]: renderAddChild, [AppState.PRIMARY_PROFILE]: renderPrimaryProfile, [AppState.STUDENT_INVITE]: renderStudentInvite, [AppState.FAMILY_DASHBOARD_INTRO]: renderFamilyDashboardIntro, [AppState.FAMILY_DASHBOARD_MISSIONS]: renderFamilyDashboardMissions, [AppState.FAMILY_DASHBOARD_DEPTH]: renderFamilyDashboardDepth, [AppState.FAMILY_SUMMARY]: renderFamilySummary, [AppState.STUDENT_ENTRY]: renderStudentEntry, [AppState.STUDENT_WELCOME]: renderStudentWelcome, [AppState.STUDENT_PRIVACY]: renderStudentPrivacy, [AppState.STUDENT_AGREEMENT]: renderStudentAgreement, [AppState.STUDENT_PROFILE]: renderStudentProfile, [AppState.STUDENT_MISSION]: renderStudentMission, [AppState.STUDENT_ARTIFACT]: renderStudentArtifact, [AppState.STUDENT_READY]: renderStudentReady
  };
  screen.innerHTML = views[currentState](); screen.querySelectorAll(".reveal").forEach((item, index) => item.style.setProperty("--reveal-index", index)); bindStateEvents();
}

function renderIntro() { return `<div class="intro-reveal" aria-labelledby="screen-title"><div class="intro-logo-stage"><span class="intro-rule intro-rule-top"></span><span class="intro-logo-frame"><img class="intro-logo" src="${ASSETS.logo}" alt="DIGIZEN" id="screen-title"></span><span class="intro-rule intro-rule-bottom"></span></div><p class="intro-microcopy">Preparando el espacio familiar.</p><button class="intro-skip" type="button" data-next="${AppState.WELCOME}">Comenzar</button></div>`; }
function renderAdaScene() {
  const media = ADA_VIDEO.src
    ? `<video class="ada-video" src="${ADA_VIDEO.src}" poster="${ADA_VIDEO.poster}" autoplay muted playsinline preload="metadata" aria-label="ADA saluda a la familia"></video>`
    : `<img class="ada-full" src="${ASSETS.adaFull}" alt="ADA, personaje guía de DIGIZEN">`;
  return `<aside class="ada-stage reveal" aria-label="ADA, guía de DIGIZEN"><span class="ada-grid"></span><span class="ada-beam"></span><span class="ada-orbit orbit-one"></span><span class="ada-orbit orbit-two"></span><span class="ada-orbit orbit-three"></span>${media}<div class="ada-cue"><span class="ada-cue-dot"></span><span class="sound-wave"><i></i><i></i><i></i><i></i><i></i></span><span>${ADA_VIDEO.src ? "ADA te da la bienvenida" : "ADA está lista para saludarte"}</span>${ADA_VIDEO.src ? `<button class="audio-toggle" type="button" data-ada-audio aria-pressed="false">Activar audio</button>` : ""}</div></aside>`;
}
function renderWelcome() { return `<div class="layout"><div class="copy intro-copy"><span class="kicker reveal"><span class="pulse-dot"></span> Bienvenida familiar</span><h1 class="reveal" id="screen-title">Hola. Soy ADA.</h1><p class="lead reveal">Voy a acompañar a tu hijo a practicar decisiones sobre su vida digital.</p><p class="body-copy reveal">A ti te ayudaré a estar presente con contexto, sin convertir su proceso en una revisión constante.</p><aside class="quote-note reveal">Porque cuidar no siempre significa mirar más. A veces significa conversar mejor.</aside><div class="actions reveal"><button class="btn cyan" data-next="${AppState.WHAT_IS}">Entender DIGIZEN</button></div></div>${renderAdaScene()}</div>`; }
function flowCard(number, title, text, color) { return `<article class="flow-card" style="--delay:${Number(number) * 100}ms"><i style="--c:${color}">${number}</i><strong>${title}</strong><span>${text}</span></article>`; }
function renderWhatIs() { return `<div class="layout single"><div class="copy"><span class="kicker reveal"><span class="pulse-dot"></span> Práctica guiada</span><h2 class="reveal" id="screen-title">DIGIZEN no pone candados.</h2><p class="display-subtitle reveal">Practica criterio.</p><p class="lead reveal">Tu hijo ya vive decisiones digitales en chats, juegos, fotos, grupos, redes e IA.</p><p class="body-copy reveal">Los controles pueden ayudar a poner límites. Las reglas pueden orientar. Pero el criterio se forma practicando decisiones, por edad, antes de que la presión llegue.</p><div class="flow-strip" aria-label="Cómo funciona DIGIZEN">${flowCard("1", "Misiones por edad", "Situaciones acordes a su momento y autonomía.", "var(--blue)")}${flowCard("2", "Dilemas reales", "Espacio para pensar antes de que la presión llegue.", "var(--violet)")}${flowCard("3", "Artefactos para conversar", "Una conclusión concreta para acompañar en familia.", "var(--coral)")}</div><div class="actions reveal"><button class="btn cyan" data-next="${AppState.ADA_DESIGN}">Ver cómo funciona</button></div></div></div>`; }
function renderAdaDesign() {
  const bullets = ["Mantiene el foco de cada misión.", "Promueve pensamiento crítico, no respuestas automáticas.", "Detecta lenguaje que requiere cuidado.", "Refuerza respeto, responsabilidad y convivencia digital."];
  return `<div class="layout single"><div class="copy wide-copy ada-design-layout"><div class="ada-design-main"><span class="kicker reveal"><span class="pulse-dot"></span> Diseño con seguridad</span><h2 class="reveal" id="screen-title">ADA no es una IA abierta.</h2><p class="display-subtitle reveal">Es un copiloto diseñado para aprender con seguridad.</p><p class="lead reveal">ADA acompaña misiones de ciudadanía y salud digital. No conversa de cualquier tema, no improvisa fuera del propósito de DIGIZEN y no sustituye el criterio de un adulto.</p><p class="body-copy reveal">ADA no conversa para sacar información. Conversa para guiar una misión. Su sistema de seguridad ayuda a mantener la conversación dentro del tema, identificar lenguaje no adecuado o discriminatorio y promover reflexión, respeto y buenas prácticas digitales.</p><ul class="check-list reveal">${bullets.map(bullet => `<li>${bullet}</li>`).join("")}</ul><div class="actions reveal"><button class="btn cyan" data-next="${AppState.PRIVACY_WHY}">Entender la privacidad</button></div></div><aside class="ada-note ada-trust-note reveal"><img src="${ASSETS.adaProfile}" alt="Retrato de ADA"><strong>La meta no es que tu hijo hable con una IA cualquiera. La meta es que practique criterio en un entorno diseñado para cuidarlo.</strong></aside></div></div>`;
}
function renderPrivacyWhy() { return `<div class="layout single"><div class="copy wide-copy"><span class="kicker reveal"><span class="pulse-dot"></span> Privacidad con propósito</span><h2 class="reveal" id="screen-title">Si siente que lo estás espiando, no va a pensar igual.</h2><p class="lead reveal">ADA no está diseñada para revisar todo lo que piensa o responde tu hijo.</p><p class="body-copy reveal">Si cada pregunta, error o duda puede convertirse en algo que el adulto leerá después, tu hijo aprende a cuidar sus respuestas. No practica criterio: practica defensa.</p><p class="body-copy reveal">El espacio con ADA necesita privacidad para que pueda pensar, equivocarse, ordenar ideas y construir una conclusión propia: su artefacto. Por eso DIGIZEN protege su espacio privado y te muestra lo necesario para acompañar mejor.</p><aside class="icon-note reveal"><span class="note-icon" aria-hidden="true">✦</span><p><strong>Privacidad no significa abandono.</strong><br>Significa que tu hijo practica con ADA, y tú recibes información útil para acompañarlo.</p></aside><div class="actions reveal"><button class="btn cyan" data-next="${AppState.PRIVACY_VIEW}">Qué voy a ver</button></div></div></div>`; }
function renderPrivacyView() {
  const visible = ["Avance de misiones.", "Temas trabajados.", "Artefactos que tu hijo valida.", "Guías para conversar.", "Historial de misiones completadas.", "Señales que requieran cuidado adulto."];
  const privateItems = ["Conversaciones completas con ADA.", "Respuestas íntimas pregunta por pregunta.", "Borradores privados.", "Actividad fuera de DIGIZEN.", "Rankings o comparaciones.", "Diagnósticos o calificaciones psicológicas."];
  const list = (items, modifier) => `<section class="privacy-list privacy-editorial ${modifier}"><h3>${modifier ? "No verás por defecto" : "Sí verás"}</h3><ul>${items.map((item, index) => `<li style="--delay:${90 + index * 55}ms">${item}</li>`).join("")}</ul></section>`;
  return `<div class="layout single"><div class="copy wide-copy"><span class="kicker reveal"><span class="pulse-dot"></span> Visibilidad útil</span><h2 class="reveal" id="screen-title">Verás lo necesario para acompañar.</h2><p class="display-subtitle reveal">No todo su proceso privado.</p><div class="privacy-grid reveal">${list(visible, "")}<span class="privacy-divider"></span>${list(privateItems, "private-list")}</div><aside class="quote-note reveal">La meta no es saberlo todo. Es saber cómo abrir la conversación correcta.</aside><div class="actions reveal"><button class="btn cyan" data-next="${AppState.ARTIFACT}">Ver qué es un artefacto</button></div></div></div>`;
}
function artifactExample() { return ({ primary: "Antes de compartir algo, puedo pensar si ayuda, lastima o confunde.", middle: "No todo lo que publico tiene que buscar reacción.", high: "Puedo separar mi vida privada de mi presencia pública." })[onboardingData.selectedArtifactAge]; }
function artifactTab(value, label) { return `<button class="choice-btn artifact-tab" type="button" data-artifact-age="${value}" aria-pressed="${onboardingData.selectedArtifactAge === value}">${label}</button>`; }
function renderArtifact() { return `<div class="layout single"><div class="copy wide-copy artifact-layout"><div class="artifact-main"><span class="kicker reveal"><span class="pulse-dot"></span> Lo que construyó</span><h2 class="reveal" id="screen-title">No verás todo lo que habló con ADA.</h2><p class="display-subtitle reveal">Verás lo que construyó.</p><p class="lead reveal">Un artefacto es una representación breve de una reflexión o conclusión a la que llegó tu hijo a partir del diálogo y la guía de ADA.</p><p class="body-copy reveal">No es todo lo que conversó. Es una forma clara de mostrar una idea que construyó durante la misión y que él o ella valida al cierre. Misión tras misión, esos bloques ayudan a construir su criterio digital.</p><section class="artifact-card reveal"><div class="artifact-tabs" role="group" aria-label="Ejemplos por etapa">${artifactTab("primary", "Primaria alta")}${artifactTab("middle", "Secundaria")}${artifactTab("high", "Preparatoria")}</div><p class="artifact-quote" id="artifactExample">“${artifactExample()}”</p></section><div class="actions reveal"><button class="btn cyan" data-next="${AppState.CARE_SIGNALS}">Entender las señales de cuidado</button></div></div><aside class="icon-note artifact-note reveal"><span class="note-icon" aria-hidden="true">✦</span><p>El artefacto no muestra toda su conversación privada. Muestra una conclusión suficiente para que puedas acompañar mejor.</p></aside></div></div>`; }
function renderCareSignals() {
  const levels = [["01", "Señal educativa", "Conviene conversar."], ["02", "Acompañamiento recomendado", "Te damos una forma de abrir el tema."], ["03", "Cuidado adulto", "La prioridad es proteger y escalar con criterio humano."]];
  return `<div class="layout single"><div class="copy wide-copy care-signals-layout"><div class="care-signals-main"><span class="kicker reveal"><span class="pulse-dot"></span> Acompañamiento con criterio</span><h2 class="reveal" id="screen-title">Si algo requiere cuidado adulto,</h2><p class="display-subtitle reveal">no te dejamos solo.</p><p class="lead reveal">DIGIZEN no diagnostica, no acusa y no promete riesgo cero.</p><p class="body-copy reveal">Pero privacidad no significa silencio absoluto. Si aparece una señal delicada dentro de la experiencia, ADA puede activar una recomendación de acompañamiento para que sepas cómo intervenir con cuidado.</p><div class="signal-grid reveal">${levels.map(([number, title, text]) => `<article class="signal-card"><span>${number}</span><strong>${title}</strong><p>${text}</p></article>`).join("")}</div><div class="actions reveal"><button class="btn cyan" data-next="${AppState.AGREEMENT}">Hacer el acuerdo</button></div></div><aside class="ada-note care-signal-note reveal"><img src="${ASSETS.adaProfile}" alt="Retrato de ADA"><strong>La notificación no está diseñada para exhibir a tu hijo. Está diseñada para ayudarte a actuar mejor.</strong></aside></div></div>`;
}
function renderAgreement() { return `<div class="agreement-layout agreement-redesign" id="agreementRoot" style="--hold-alpha:0"><div class="agreement-intro"><span class="kicker reveal"><span class="pulse-dot"></span> Acuerdo familiar</span><h2 class="reveal" id="screen-title">Hagamos un acuerdo antes de empezar.</h2><p class="lead reveal">Lo que veas en DIGIZEN debe servir para acercarte, no para interrogar.</p><p class="body-copy reveal">Piensa en tu hijo. Lee este acuerdo como si se lo dijeras de frente.</p></div><div class="agreement-visual reveal"><img src="${ASSETS.agreement}" alt="Dos manos haciendo una promesa de acompañamiento"></div><div class="agreement-content"><section class="agreement-card reveal"><h3>Acuerdo de acompañamiento</h3><p class="body-copy">Quiero acompañarte sin invadirte.<br>Quiero que sepas que puedes pensar, equivocarte y pedirme ayuda si algo se complica.<br><br>Usaré lo que DIGIZEN me muestre para acercarme a ti, no para revisar todo lo que haces.<br><br>Respetaré tu espacio de reflexión con ADA.<br><br>Si aparece una señal que necesite cuidado adulto, voy a actuar con calma, protección y criterio.</p></section><div class="hold-wrap reveal"><button class="hold-button" id="holdButton" type="button" aria-label="Mantén presionado para sellar la promesa"><span id="holdLabel">Lo prometo</span></button><p class="body-copy">Mantén presionado el botón para sellar la promesa.</p></div></div></div>`; }
function renderAgreementComplete() { return `<div class="layout single"><div class="complete-panel reveal"><span class="complete-check">✓</span><span class="kicker"><span class="pulse-dot"></span> Acuerdo hecho</span><h2 id="screen-title">Promesa guardada.</h2><p class="lead">Ahora preparemos la entrada de tu hijo.</p><div class="actions"><button class="btn cyan" data-next="${AppState.ADD_CHILD}">Continuar</button></div></div></div>`; }
function choiceButton(value, label) { return `<button class="choice-btn" type="button" data-stage="${value}" aria-pressed="${onboardingData.stage === value}">${label}</button>`; }
function renderGradeChoices() { if (!onboardingData.stage) return `<span class="fine-print">Elige una etapa para seleccionar grado / nivel.</span>`; const grades = onboardingData.stage === "primary" ? ["4.º", "5.º", "6.º"] : ["1.º", "2.º", "3.º"]; return `<span class="choice-label">Grado / nivel</span><div class="choice-grid" role="group" aria-label="Grado escolar">${grades.map(grade => `<button class="choice-btn" type="button" data-grade="${grade}" aria-pressed="${onboardingData.grade === grade}">${grade}</button>`).join("")}</div>`; }
function renderAddChild() {
  const isEditing = editingChild && onboardingData.childName, name = escapeHtml(onboardingData.childName || "tu hijo");
  return `<div class="layout single"><form class="copy form-grid" id="childForm"><span class="kicker reveal"><span class="pulse-dot"></span> Perfil inicial</span><h2 class="reveal" id="screen-title">${isEditing ? `Ajustemos los datos de ${name}.` : "Ahora preparemos la entrada de tu hijo."}</h2><p class="lead reveal">La edad define el nivel de autonomía. En primaria alta puedes acompañarlo a crear su espacio. En secundaria y prepa, le enviarás una invitación para que empiece desde su propio acceso.</p><div class="field reveal"><label for="childName">Nombre</label><input class="text-input" id="childName" name="childName" autocomplete="given-name" value="${escapeHtml(onboardingData.childName)}" placeholder="Mateo"></div><div class="field reveal"><span class="choice-label">Etapa</span><div class="choice-grid" role="group" aria-label="Etapa escolar">${choiceButton("primary", "Primaria alta")}${choiceButton("middle", "Secundaria")}${choiceButton("high", "Preparatoria")}</div></div><div class="field reveal" id="gradeField">${renderGradeChoices()}</div><div class="actions reveal"><button class="btn cyan" id="addChildCta" type="submit" disabled>${isEditing ? "Guardar cambios" : "Continuar"}</button></div></form></div>`;
}
function renderPrimaryProfile() {
  const child = escapeHtml(onboardingData.childName || "Mateo");
  return `<div class="layout single"><div class="copy profile-copy"><span class="kicker reveal"><span class="pulse-dot"></span> Perfil acompañado</span><h2 class="reveal" id="screen-title">En primaria alta, empiezan juntos.</h2><p class="lead reveal">Tú ayudas a crear su acceso y elegir un avatar. Después, ADA le explicará a tu hijo que este es su espacio para practicar decisiones digitales con confianza.</p><p class="fine-print reveal">El avatar no es una foto real. Es una forma segura de reconocer su perfil.</p><div class="avatar-grid reveal" role="group" aria-label="Avatares prediseñados">${ASSETS.avatars.map((avatar, index) => `<button class="avatar-btn" type="button" style="--avatar-index:${index}" data-avatar="${avatar}" aria-label="Seleccionar avatar ${index + 1}" aria-pressed="${onboardingData.avatar === avatar}"><img src="${avatar}" alt=""></button>`).join("")}</div><div class="summary-card reveal"><img src="${selectedAvatar()}" alt="Avatar seleccionado" id="summaryAvatar"><div><strong>${child}</strong><p class="fine-print">${escapeHtml(gradeLabel())}</p></div><button class="icon-btn" type="button" data-edit-child aria-label="Editar datos de ${child}">✎</button></div><div class="actions reveal"><button class="btn cyan" id="createProfile" ${onboardingData.avatar ? "" : "disabled"}>Crear perfil</button><span class="success-note" id="profileReady">✓ Perfil listo. Ahora tu hijo puede conocer a ADA.</span></div></div></div>`;
}
function methodCard(method, title, text) { return `<button class="method-card ${onboardingData.inviteMethod === method ? "is-selected" : ""}" type="button" data-method="${method}"><strong>${title}</strong><span class="fine-print">${text}</span></button>`; }
function invitationMessage() { return `Te compré DIGIZEN para que tengas un espacio con ADA y practiques decisiones sobre tu vida digital.\n\nNo es para que yo lea todo. Es para que tengas más criterio cuando yo no estoy.\n\nEntra aquí cuando puedas:\n${JOIN_URL}`; }
function renderInvitePanel() { if (onboardingData.inviteMethod === "email") return `<div class="field"><label for="studentEmail">Correo del alumno</label><input class="text-input" id="studentEmail" type="email" placeholder="nombre@correo.com"></div><p class="fine-print">Demo: no se enviará ningún correo real.</p><div class="actions"><button class="btn secondary" id="simulateEmail">Preparar invitación</button><span class="success-note" id="emailStatus">✓ Invitación preparada</span></div>`; if (onboardingData.inviteMethod === "whatsapp") return `<p class="body-copy">Abriremos WhatsApp con el mensaje preparado. DIGIZEN no tendrá acceso a tus conversaciones.</p><div class="actions"><button class="btn secondary" id="openWhatsapp">Abrir WhatsApp</button></div>`; return `<div class="link-box"><span class="fake-url">${JOIN_URL}</span><button class="btn secondary" id="copyLink">Copiar enlace</button></div><p class="success-note" id="copyStatus">✓ Copiado</p>`; }
function renderStudentInvite() { const child = escapeHtml(onboardingData.childName || "Mateo"); return `<div class="layout single"><div class="copy"><span class="kicker reveal"><span class="pulse-dot"></span> Autonomía progresiva</span><h2 class="reveal" id="screen-title">A esta edad, necesita entrar desde su propio espacio.</h2><p class="lead reveal">Tú envías la invitación. ${child} crea su acceso.</p><p class="body-copy reveal">Esto ayuda a que ADA no se sienta como una extensión del adulto, sino como un espacio de práctica personal.</p><div class="method-grid reveal" role="group" aria-label="Método de invitación">${methodCard("link", "Copiar enlace", "Compártelo por el canal que prefieras.")}${methodCard("whatsapp", "Enviar por WhatsApp", "Abre WhatsApp con el mensaje listo.")}${methodCard("email", "Enviar por correo", "Prepara una invitación simulada.")}</div><div class="invite-panel reveal" id="invitePanel">${renderInvitePanel()}</div><div class="actions reveal"><button class="btn cyan" data-next="${AppState.FAMILY_DASHBOARD_INTRO}">Ya compartí la invitación</button></div></div></div>`; }
function dashboardExplainer(kicker, title, subtitle, lead, preview, aside, next, cta) { return `<div class="layout single dashboard-explainer"><div class="copy dashboard-explainer-copy"><span class="kicker reveal"><span class="pulse-dot"></span> ${kicker}</span><h2 class="reveal" id="screen-title">${title}</h2><p class="display-subtitle reveal">${subtitle}</p><p class="lead reveal">${lead}</p>${preview}<div class="actions reveal"><button class="btn cyan" data-next="${next}">${cta}</button></div></div><aside class="dashboard-explainer-aside reveal">${aside}</aside></div>`; }
function renderFamilyDashboardIntro() {
  return dashboardExplainer("Tu panel familiar · 1 de 3", "Cuando termine una misión, sabrás cómo acompañar sin leerlo todo.", "No recibirás una lupa. Recibirás una puerta para conversar.", "El panel empieza con un panorama semanal: qué territorios ha explorado, qué temas aparecieron y cuál es tu rol para acompañar esta etapa.", `<section class="dashboard-onboarding-preview overview-preview reveal"><span>Esta semana en DIGIZEN</span><div><i>◌</i><p><strong>Panorama de práctica</strong>Temas explorados, mapa acumulado y dos misiones completadas.</p></div></section>`, `<span class="aside-step">1</span><h3>Primero, el panorama.</h3><p>El mapa no califica a tu hijo. Te ayuda a ver qué áreas ha ido practicando con el tiempo.</p><ul><li>Estado semanal</li><li>Mapa acumulado</li><li>Temas de la semana</li></ul>`, AppState.FAMILY_DASHBOARD_MISSIONS, "Ver las misiones");
}
function renderFamilyDashboardMissions() {
  return dashboardExplainer("Tu panel familiar · 2 de 3", "Cada misión se convierte en una forma concreta de acompañar.", "Tema, idea propia y una entrada natural para conversar.", "No verás una transcripción. Verás una conclusión que tu hijo validó y una frase cotidiana que puedes usar si quieres abrir el tema en casa.", `<section class="dashboard-onboarding-preview mission-preview reveal"><div><span>01</span><p>Reconocer cuándo una oferta digital puede pedir más de lo que parece.</p></div><div><i>✦</i><p><strong>Artefacto validado</strong>Una idea que sí representa lo que pensó.</p></div><div><i>↗</i><p><strong>Para iniciar la conversación</strong>Una entrada desde el mundo adulto, no una pregunta de vigilancia.</p></div></section>`, `<span class="aside-step">2</span><h3>Después, una misión a la vez.</h3><p>Lo importante de cada misión cabe en una lectura breve. Tú eliges cuál conversación vale la pena abrir.</p><blockquote>“La idea no es saberlo todo. Es poder estar cerca.”</blockquote>`, AppState.FAMILY_DASHBOARD_DEPTH, "Ver la profundidad opcional");
}
function renderFamilyDashboardDepth() {
  return dashboardExplainer("Tu panel familiar · 3 de 3", "Lo importante se ve primero. La profundidad aparece cuando tú la abres.", "No todo requiere el mismo tiempo ni la misma conversación.", "Si quieres seguir, cada misión guarda una guía para conversar, un reto familiar y contexto adicional. Si no, la idea principal ya hizo su trabajo.", `<section class="dashboard-onboarding-preview depth-preview reveal"><strong>Profundiza solo si lo necesitas</strong><span>↗ Seguir la conversación <b>⌄</b></span><span>🧩 Reto familiar · 10 min <b>⌄</b></span><span>📖 Solo quiero la teoría <b>⌄</b></span></section>`, `<span class="aside-step">3</span><h3>Tú eliges cuánto abrir.</h3><p>La profundidad está disponible para acompañarte, no para convertir el panel en otra tarea pendiente.</p><blockquote>Una buena conversación puede terminar sin confesión, regla ni moraleja.</blockquote>`, AppState.FAMILY_SUMMARY, "Entrar al panel familiar");
}
function reportStudentButton(key, label, detail) {
  const active = onboardingData.reportStudent === key;
  return `<button class="report-student ${active ? "is-active" : ""}" type="button" data-report-student="${key}" aria-pressed="${active}"><img src="${reportAvatars[key]}" alt=""><span><strong>${label}</strong><small>${detail}</small></span></button>`;
}
function reportAccordion(key, label, content) { return `<section class="report-accordion"><button type="button" data-report-accordion="${key}" aria-expanded="false"><span>${label}</span><b>⌄</b></button><div id="${key}Detail" hidden>${content}</div></section>`; }
function reportChallenge(mission, key) { return reportAccordion(`familyChallenge-${key}`, "🧩 Reto familiar · 10 min", `<strong>El reto: ${mission.challengeTitle}</strong><ol>${mission.challengeSteps.map(step => `<li>${step}</li>`).join("")}</ol><p class="accordion-goal"><b>Objetivo:</b> ${mission.challengeGoal}</p>`); }
function reportTheory(mission, key) { return reportAccordion(`adultTheory-${key}`, "📖 Solo quiero la teoría", `<strong>${mission.theoryTitle}</strong><p>${mission.theoryText}</p>`); }
function radialPoint(radius, index, total = 6) { const angle = (-90 + index * 360 / total) * Math.PI / 180; return { x: 120 + Math.cos(angle) * radius, y: 120 + Math.sin(angle) * radius }; }
function roundedSnowflakePath(values, radius) {
  const points = values.map((value, index) => radialPoint(radius * value / 100, index, values.length));
  const midpoint = (a, b) => ({ x: (a.x + b.x) / 2, y: (a.y + b.y) / 2 });
  const start = midpoint(points.at(-1), points[0]);
  return `M ${start.x.toFixed(1)} ${start.y.toFixed(1)} ${points.map((point, index) => { const next = midpoint(point, points[(index + 1) % points.length]); return `Q ${point.x.toFixed(1)} ${point.y.toFixed(1)} ${next.x.toFixed(1)} ${next.y.toFixed(1)}`; }).join(" ")} Z`;
}
function renderSnowflake(studentKey, report) {
  const coverage = familyReportCoverage[studentKey];
  const isClimate = onboardingData.reportVisual === "climate";
  const themes = isClimate ? dashboardMetricSets.climate : dashboardMetricSets.skills;
  const primaryMetric = activeDashboardMetric(studentKey, report);
  const values = isClimate ? coverage.values.slice(0, 6) : coverage.values.slice(6);
  const outer = roundedSnowflakePath(Array(themes.length).fill(100), 76);
  const inner = roundedSnowflakePath(Array(themes.length).fill(50), 76);
  const data = roundedSnowflakePath(values, 76);
  const axisIcons = themes.map(([key, icon, climate, skill], index) => { const point = radialPoint(99, index, themes.length); return `<g class="snowflake-axis-icon"><title>${isClimate ? climate : skill}</title><circle cx="${point.x.toFixed(1)}" cy="${point.y.toFixed(1)}" r="12"></circle><text x="${point.x.toFixed(1)}" y="${(point.y + 4).toFixed(1)}">${icon}</text></g>`; }).join("");
  return `<section class="snowflake-card" aria-label="Mapa acumulado de práctica de ${report.name}"><header><span>${isClimate ? "Clima digital acumulado" : "Habilidades con IA acumuladas"}</span><div class="visual-toggle" role="group" aria-label="Mapa a visualizar"><button data-report-view="climate" aria-pressed="${isClimate}">Clima</button><button data-report-view="tree" aria-pressed="${!isClimate}">Habilidades</button></div></header><div class="snowflake-body"><svg viewBox="0 0 240 240" role="img" aria-label="${themes.length} áreas de práctica acumulada, sin calificaciones"><path class="snowflake-grid outer" d="${outer}"></path><path class="snowflake-grid inner" d="${inner}"></path>${Array.from({ length: themes.length }, (_, index) => { const point = radialPoint(76, index, themes.length); return `<line x1="120" y1="120" x2="${point.x.toFixed(1)}" y2="${point.y.toFixed(1)}"></line>`; }).join("")}<path class="snowflake-fill" d="${data}"></path><circle cx="120" cy="120" r="12"></circle><text x="120" y="123">${primaryMetric[1]}</text>${axisIcons}</svg><ul>${themes.map(([key, icon, climate, skill]) => `<li class="${coverage.featured.includes(key) ? "is-featured" : ""}"><i>${icon}</i><span>${isClimate ? climate : skill}</span></li>`).join("")}</ul></div><p>Refleja territorios practicados mediante misiones y artefactos validados; no es una calificación.</p></section>`;
}
function primaryMission(studentKey, report) {
  const titles = { leo: "Una oferta que parece un regalo", sofia: "El algoritmo de la belleza", mateo: "Quién lee tu currículum primero" };
  return { id: `${studentKey}-01`, title: titles[studentKey], topic: report.topic, skill: report.node, icon: report.icon, context: report.context, artifact: report.artifact, question: report.question, situation: report.situation, close: report.close, challengeTitle: report.challengeTitle, challengeSteps: report.challengeSteps, challengeGoal: report.challengeGoal, theoryTitle: report.theoryTitle, theoryText: report.theoryText };
}
function weeklyMissions(studentKey, report) { return [primaryMission(studentKey, report), { id: `${studentKey}-02`, ...secondaryWeeklyMissions[studentKey] }]; }
function conversationGuide(mission, key) { const guide = abrirGuides[key]; return reportAccordion(`conversation-${key}`, "↗ Seguir la conversación", `<div class="abrir-guide"><section><span>Comparte algo tuyo</span><p>“${guide.relate}”</p></section><section><span>Después, una sola invitación</span><p>“${guide.invite}”</p></section><section><span>Si responde, refleja antes de avanzar</span><p>“${guide.reflect}”</p></section><section><span>Si no quiere seguir</span><p>“${guide.exit}”</p></section></div>`); }
function missionDepth(mission, key) { return reportAccordion(`depth-${key}`, "Profundiza solo si lo necesitas", `<div class="mission-depth-options">${conversationGuide(mission, key)}${reportChallenge(mission, key)}${reportTheory(mission, key)}</div>`); }
function renderMissionCard(mission, index) {
  const key = mission.id;
  const guide = abrirGuides[key];
  return `<article class="mission-card"><header class="mission-head"><div class="mission-title"><span>Misión ${String(index + 1).padStart(2, "0")} · Completada</span><h3>${mission.title}</h3></div><div class="mission-meta"><div class="mission-chips"><span>${mission.topic}</span><span>${mission.skill}</span></div><i aria-hidden="true">${mission.icon}</i></div></header><div class="mission-trio"><p class="mission-brief">${missionBriefs[key]}</p><section class="mission-artifact"><span class="mission-label"><i class="label-icon" aria-hidden="true">✦</i> Artefacto validado</span><p>“${mission.artifact}”</p></section><section class="mission-opener"><span class="mission-label"><i class="label-icon" aria-hidden="true">↗</i> Para iniciar la conversación</span><p>“${guide.opener}”</p></section></div><section class="mission-base">${missionDepth(mission, key)}</section></article>`;
}
function renderFamilySummary() {
  const studentKey = onboardingData.reportStudent;
  const report = familyReportData[studentKey];
  const activeMetric = activeDashboardMetric(studentKey, report);
  const missions = weeklyMissions(studentKey, report);
  return `<div class="family-report dashboard-proposal"><header class="family-report-head"><div><span class="kicker"><span class="pulse-dot"></span> Reporte familiar · semana del 8 al 14 de septiembre</span><h2 id="screen-title">Así va su práctica digital.</h2><p class="display-subtitle">Elige a un alumno para ver su semana y las misiones que construyó.</p></div></header><section class="report-selector" aria-label="Alumnos de la familia"><span>Alumnos</span><div>${reportStudentButton("leo", "Leo · 5.º primaria", "2 misiones esta semana")}${reportStudentButton("sofia", "Sofía · 1.º secundaria", "2 misiones esta semana")}${reportStudentButton("mateo", "Mateo · 2.º prepa", "2 misiones esta semana")}</div></section><section class="dashboard-student-hero"><div class="student-dashboard-profile"><img src="${reportAvatars[studentKey]}" alt="Avatar de ${report.name}"><div><span>Esta semana</span><h3>${report.name}</h3><p>${report.level}</p></div></div><div class="student-week-status"><span class="status-overline">Estado de acompañamiento</span><h3>${activeMetric[1]} ${onboardingData.reportVisual === "climate" ? activeMetric[2] : activeMetric[3]}</h3><p>${report.name} completó <strong>${missions.length} misiones</strong>. Tu rol esta semana: <strong>${report.role}</strong>.</p><div class="status-chips"><span>${missions[0].topic}</span><span>${missions[1].topic}</span></div></div>${renderSnowflake(studentKey, report)}</section><section class="missions-week"><header><div><span class="kicker"><span class="pulse-dot"></span> Misiones de esta semana</span><h2>Una misión, una forma concreta de acompañar.</h2></div><p>Abre solo la profundidad que necesites.</p></header><div class="mission-list">${missions.map((mission, index) => renderMissionCard(mission, index)).join("")}</div></section><div class="actions report-footer"><button class="btn secondary" type="button" data-student-preview>Ver el onboarding de ${escapeHtml(onboardingData.childName || report.name)}</button></div></div>`;
}

function studentStageChoice(value, label) { return `<button class="choice-btn" type="button" data-student-stage="${value}" aria-pressed="${onboardingData.stage === value}">${label}</button>`; }
function renderStudentEntry() { return `<div class="student-shell"><div class="copy student-copy"><span class="kicker reveal"><span class="pulse-dot"></span> Tu espacio con ADA</span><h1 class="reveal" id="screen-title">Este es tu espacio con ADA.</h1><p class="lead reveal">Aquí vas a practicar decisiones sobre tu vida digital. No es una clase larga ni un lugar para que alguien te regañe.</p><section class="student-level reveal"><strong>Antes de empezar, confirma tu nivel.</strong><p class="fine-print">Esto ayuda a que ADA use ejemplos y lenguaje adecuados para ti.</p><div class="choice-grid" role="group" aria-label="Confirmar nivel">${studentStageChoice("primary", "Primaria alta")}${studentStageChoice("middle", "Secundaria")}${studentStageChoice("high", "Preparatoria")}</div></section><div class="actions reveal"><button class="btn cyan" id="studentEntryCta">Conocer a ADA</button></div></div>${renderAdaScene()}</div>`; }
function studentWelcomeCopy() { return ({ primary: ["Hola. Soy ADA.", "Voy a ayudarte a entender mejor lo que pasa cuando juegas, ves videos, das like, compartes algo o pides ayuda.", "No vengo a regañarte. Vamos a pensar juntos.", "Empezar"], middle: ["Hola. Soy ADA.", "No estoy aquí para juzgar tus redes ni decirte que todo está mal.", "Mi trabajo es ayudarte a ver cómo funcionan algunas decisiones digitales antes de que se vuelvan problema.", "Continuar"], high: ["Qué tal. Soy ADA.", "Probablemente no necesitas que alguien te explique cómo usar internet.", "Mi función es auditar contigo cómo funcionan algunos sistemas digitales, qué información procesan y qué decisiones siguen bajo tu control.", "Entendido"] })[onboardingData.stage || "middle"]; }
function renderStudentWelcome() { const [title, lead, body, cta] = studentWelcomeCopy(); return `<div class="student-shell"><div class="copy student-copy"><span class="kicker reveal"><span class="pulse-dot"></span> ADA · ${studentStageLabel()}</span><h1 class="reveal" id="screen-title">${title}</h1><p class="lead reveal">${lead}</p><p class="body-copy reveal">${body}</p><div class="actions reveal"><button class="btn cyan" data-next="${AppState.STUDENT_PRIVACY}">${cta}</button></div></div>${renderAdaScene()}</div>`; }
function renderStudentPrivacy() { return `<div class="layout single student-centered"><div class="copy student-copy"><span class="kicker reveal"><span class="pulse-dot"></span> Tu privacidad</span><h2 class="reveal" id="screen-title">Tu espacio con ADA es para pensar con honestidad.</h2><p class="lead reveal">Tus papás no ven por defecto toda tu conversación ni tus respuestas privadas.</p><div class="student-info-grid reveal"><article><strong>Lo que sí puede compartirse</strong><p>Un artefacto que tú validas al terminar una misión puede ayudar a abrir una conversación en casa.</p></article><article><strong>Cuando necesitas ayuda</strong><p>Si algo necesita apoyo adulto, ADA puede ayudarte a pedirlo sin exponerte de más.</p></article></div><div class="actions reveal"><button class="btn cyan" data-next="${AppState.STUDENT_AGREEMENT}">Hacer mi acuerdo</button></div></div></div>`; }
function renderStudentAgreement() { return `<div class="agreement-layout student-agreement" id="agreementRoot" style="--hold-alpha:0"><div class="agreement-visual reveal"><img src="${ASSETS.agreement}" alt="Dos manos haciendo un acuerdo de confianza"></div><div class="copy"><span class="kicker reveal"><span class="pulse-dot"></span> Tu acuerdo</span><h2 class="reveal" id="screen-title">Un acuerdo para pensar de verdad.</h2><p class="lead reveal">Este espacio es privado para que puedas responder sin actuar perfecto.</p><p class="body-copy reveal">ADA no necesita que digas “lo correcto”. Necesita que pienses con calma, pruebes ideas y digas cuando algo no te queda claro. Si algo te preocupa o se siente demasiado grande para resolverlo solo, puedes pedir ayuda.</p><section class="agreement-card reveal"><h3>Mi acuerdo</h3><p class="body-copy">Voy a responder con honestidad, aunque no suene perfecto.<br><br>Voy a intentar pensar antes de contestar rápido.<br><br>Si algo me preocupa o necesito ayuda, puedo decirlo.</p></section><div class="hold-wrap reveal"><button class="hold-button" id="holdButton" type="button" aria-label="Mantén presionado para guardar tu acuerdo"><span id="holdLabel">Lo hago</span></button><p class="body-copy">Mantén presionado para guardar tu acuerdo.</p></div></div></div>`; }
function interestChip(value, label) { return `<button type="button" class="interest-chip" data-interest="${value}" aria-pressed="${onboardingData.studentInterests.includes(value)}">${label}</button>`; }
function renderStudentProfile() { const name = escapeHtml(onboardingData.studentName || onboardingData.childName || ""); return `<div class="layout single student-centered"><form class="copy student-copy form-grid" id="studentProfileForm"><span class="kicker reveal"><span class="pulse-dot"></span> Ajustemos la conversación</span><h2 class="reveal" id="screen-title">Para ajustar la conversación, necesito conocerte un poco.</h2><div class="field reveal"><label for="studentName">¿Cómo quieres que te diga?</label><input class="text-input" id="studentName" value="${name}" placeholder="Tu nombre"></div><div class="field reveal"><span class="choice-label">¿Qué sueles hacer en línea?</span><div class="interest-grid" role="group" aria-label="Intereses">${interestChip("crear", "Crear")}${interestChip("jugar", "Jugar")}${interestChip("convivir", "Convivir")}${interestChip("explorar", "Explorar")}${interestChip("retos", "Resolver retos")}${interestChip("aprender", "Aprender")}</div></div><div class="actions reveal"><button class="btn cyan" id="studentProfileCta" type="submit" disabled>Guardar</button></div></form></div>`; }
function renderStudentMission() { return `<div class="layout single student-centered"><div class="copy student-copy"><span class="kicker reveal"><span class="pulse-dot"></span> Una misión a la vez</span><h2 class="reveal" id="screen-title">Cada misión empieza con una situación.</h2><p class="display-subtitle reveal">No con una respuesta correcta.</p><p class="lead reveal">ADA te mostrará un dilema, un dato breve o una escena parecida a algo que puede pasar en internet.</p><div class="mission-steps reveal"><span><b>1</b> Piensas</span><span><b>2</b> Respondes</span><span><b>3</b> Ajustas</span><span><b>4</b> Cierras con una idea propia</span></div><ul class="student-promise reveal"><li>No tienes que sonar perfecto.</li><li>Puedes cambiar de opinión.</li><li>No publicar también puede ser una decisión.</li></ul><div class="actions reveal"><button class="btn cyan" data-next="${AppState.STUDENT_ARTIFACT}">Crear mi artefacto</button></div></div></div>`; }
function renderStudentArtifact() { return `<div class="layout single student-centered"><div class="copy student-copy"><span class="kicker reveal"><span class="pulse-dot"></span> Tu idea, en tus palabras</span><h2 class="reveal" id="screen-title">Al final de cada misión, vas a crear un artefacto.</h2><p class="lead reveal">Es una forma breve de representar una reflexión o conclusión a la que llegaste con ayuda de ADA.</p><section class="artifact-card reveal"><span class="artifact-label">Ejemplo de artefacto</span><p class="artifact-quote">“Puedo pensar antes de reaccionar o compartir.”</p><p class="body-copy">No es copiar toda tu conversación. Es elegir una idea que sí te represente y que pueda ayudarte a explicar lo que pensaste.</p></section><aside class="quote-note reveal">Tú decides si validas el artefacto al cierre. ADA no comparte toda tu conversación.</aside><div class="actions reveal"><button class="btn cyan" data-next="${AppState.STUDENT_READY}">Empezar mi primera misión</button></div></div></div>`; }
function renderStudentReady() { const name = escapeHtml(onboardingData.studentName || onboardingData.childName || ""); return `<div class="layout single student-centered"><div class="complete-panel reveal"><span class="complete-check">✓</span><span class="kicker"><span class="pulse-dot"></span> Espacio preparado</span><h2 id="screen-title">Listo${name ? `, ${name}` : ""}.</h2><p class="lead">Tu primera misión empieza con una decisión cotidiana. No necesitas tener la respuesta perfecta.</p><div class="actions"><button class="btn cyan" id="startMission">Ver primera misión</button><button class="btn secondary" data-next="${AppState.FAMILY_SUMMARY}">Volver al resumen familiar</button></div></div></div>`; }

function bindStateEvents() {
  if (currentState === AppState.INTRO) { document.querySelector(".intro-skip").addEventListener("click", () => transitionTo(AppState.WELCOME)); introTimer = setTimeout(() => transitionTo(AppState.WELCOME), INTRO_DURATION); return; }
  screen.querySelectorAll("[data-next]").forEach(button => button.addEventListener("click", () => transitionTo(button.dataset.next)));
  screen.querySelectorAll("[data-edit-child]").forEach(button => button.addEventListener("click", () => { editingChild = true; transitionTo(AppState.ADD_CHILD); }));
  screen.querySelectorAll("[data-student-preview]").forEach(button => button.addEventListener("click", () => transitionTo(AppState.STUDENT_ENTRY)));
  if (currentState === AppState.WELCOME) bindWelcome();
  if (currentState === AppState.ARTIFACT) bindArtifact(); if (currentState === AppState.ADD_CHILD) bindAddChild(); if (currentState === AppState.PRIMARY_PROFILE) bindPrimaryProfile(); if (currentState === AppState.STUDENT_INVITE) bindStudentInvite(); if (currentState === AppState.AGREEMENT) bindAgreement(); if (currentState === AppState.STUDENT_AGREEMENT) bindAgreement(AppState.STUDENT_PROFILE, "Acuerdo guardado.", "studentAgreementAccepted"); if (currentState === AppState.STUDENT_ENTRY) bindStudentEntry(); if (currentState === AppState.STUDENT_PROFILE) bindStudentProfile();
  if (currentState === AppState.FAMILY_SUMMARY) bindFamilyReport();
  if (currentState === AppState.STUDENT_READY) document.querySelector("#startMission").addEventListener("click", () => announce("La primera misión estará disponible en la experiencia del alumno."));
}
function bindWelcome() {
  const audioToggle = document.querySelector("[data-ada-audio]");
  const video = document.querySelector(".ada-video");
  if (!audioToggle || !video) return;
  audioToggle.addEventListener("click", () => {
    video.muted = !video.muted;
    const isOn = !video.muted;
    audioToggle.textContent = isOn ? "Silenciar" : "Activar audio";
    audioToggle.setAttribute("aria-pressed", String(isOn));
    if (isOn) video.play().catch(() => {});
  });
}
function bindStudentEntry() {
  const cta = document.querySelector("#studentEntryCta");
  screen.querySelectorAll("[data-student-stage]").forEach(button => button.addEventListener("click", () => {
    onboardingData.stage = button.dataset.studentStage;
    screen.querySelectorAll("[data-student-stage]").forEach(item => item.setAttribute("aria-pressed", String(item === button)));
  }));
  cta.addEventListener("click", () => transitionTo(AppState.STUDENT_WELCOME));
}
function bindStudentProfile() {
  const form = document.querySelector("#studentProfileForm"), name = document.querySelector("#studentName"), cta = document.querySelector("#studentProfileCta");
  function sync() { onboardingData.studentName = name.value.trim(); cta.disabled = !(onboardingData.studentName && onboardingData.studentInterests.length); }
  name.addEventListener("input", sync);
  screen.querySelectorAll("[data-interest]").forEach(button => button.addEventListener("click", () => {
    const interest = button.dataset.interest;
    onboardingData.studentInterests = onboardingData.studentInterests.includes(interest) ? onboardingData.studentInterests.filter(item => item !== interest) : [...onboardingData.studentInterests, interest];
    button.setAttribute("aria-pressed", String(onboardingData.studentInterests.includes(interest)));
    sync();
  }));
  form.addEventListener("submit", event => { event.preventDefault(); if (!cta.disabled) transitionTo(AppState.STUDENT_MISSION); });
  sync();
}
function bindFamilyReport() {
  screen.querySelectorAll("[data-report-student]").forEach(button => button.addEventListener("click", () => { onboardingData.reportStudent = button.dataset.reportStudent; render(); }));
  screen.querySelectorAll("[data-report-view]").forEach(button => button.addEventListener("click", () => { onboardingData.reportVisual = button.dataset.reportView; render(); }));
  screen.querySelectorAll("[data-report-accordion]").forEach(button => button.addEventListener("click", () => {
    const detail = document.querySelector(`#${button.dataset.reportAccordion}Detail`);
    const open = button.getAttribute("aria-expanded") === "true";
    button.setAttribute("aria-expanded", String(!open));
    detail.hidden = open;
  }));
}
function bindArtifact() { screen.querySelectorAll("[data-artifact-age]").forEach(button => button.addEventListener("click", () => { onboardingData.selectedArtifactAge = button.dataset.artifactAge; screen.querySelectorAll("[data-artifact-age]").forEach(item => item.setAttribute("aria-pressed", String(item === button))); document.querySelector("#artifactExample").textContent = `“${artifactExample()}”`; })); }
function bindAddChild() {
  const form = document.querySelector("#childForm"), nameInput = document.querySelector("#childName"), cta = document.querySelector("#addChildCta");
  function syncCta() { onboardingData.childName = nameInput.value.trim(); cta.disabled = !(onboardingData.childName && onboardingData.stage && onboardingData.grade); cta.textContent = editingChild ? "Guardar cambios" : onboardingData.stage === "primary" ? "Crear perfil acompañado" : "Preparar invitación"; }
  nameInput.addEventListener("input", syncCta);
  screen.querySelectorAll("[data-stage]").forEach(button => button.addEventListener("click", () => { onboardingData.stage = button.dataset.stage; onboardingData.grade = ""; document.querySelector("#gradeField").innerHTML = renderGradeChoices(); screen.querySelectorAll("[data-stage]").forEach(item => item.setAttribute("aria-pressed", String(item === button))); bindGradeButtons(syncCta); syncCta(); }));
  bindGradeButtons(syncCta); form.addEventListener("submit", event => { event.preventDefault(); if (!cta.disabled) { editingChild = false; transitionTo(onboardingData.stage === "primary" ? AppState.PRIMARY_PROFILE : AppState.STUDENT_INVITE); } }); syncCta();
}
function bindGradeButtons(onChange) { screen.querySelectorAll("[data-grade]").forEach(button => button.addEventListener("click", () => { onboardingData.grade = button.dataset.grade; screen.querySelectorAll("[data-grade]").forEach(item => item.setAttribute("aria-pressed", String(item === button))); onChange(); })); }
function bindPrimaryProfile() { const createButton = document.querySelector("#createProfile"); screen.querySelectorAll("[data-avatar]").forEach(button => button.addEventListener("click", () => { onboardingData.avatar = button.dataset.avatar; screen.querySelectorAll("[data-avatar]").forEach(item => item.setAttribute("aria-pressed", String(item === button))); document.querySelector("#summaryAvatar").src = onboardingData.avatar; createButton.disabled = false; })); createButton.addEventListener("click", () => { document.querySelector("#profileReady").classList.add("is-visible"); announce("Perfil listo. Ahora verás cómo funciona tu panel familiar."); setTimeout(() => transitionTo(AppState.FAMILY_DASHBOARD_INTRO), 1100); }); }
function bindStudentInvite() { screen.querySelectorAll("[data-method]").forEach(button => button.addEventListener("click", () => { onboardingData.inviteMethod = button.dataset.method; document.querySelector("#invitePanel").innerHTML = renderInvitePanel(); screen.querySelectorAll("[data-method]").forEach(item => item.classList.toggle("is-selected", item === button)); bindInvitePanelControls(); })); bindInvitePanelControls(); }
function bindInvitePanelControls() {
  const copyLink = document.querySelector("#copyLink"); if (copyLink) copyLink.addEventListener("click", async () => { try { await navigator.clipboard.writeText(JOIN_URL); } catch { window.prompt("Copia este enlace:", JOIN_URL); } const status = document.querySelector("#copyStatus"); status.classList.add("is-visible"); copyLink.textContent = "Copiado ✓"; announce("Enlace copiado."); setTimeout(() => { status.classList.remove("is-visible"); copyLink.textContent = "Copiar enlace"; }, 1500); });
  const simulateEmail = document.querySelector("#simulateEmail"); if (simulateEmail) simulateEmail.addEventListener("click", () => { simulateEmail.disabled = true; simulateEmail.textContent = "Preparando…"; setTimeout(() => { document.querySelector("#emailStatus").classList.add("is-visible"); simulateEmail.textContent = "Preparar invitación"; simulateEmail.disabled = false; announce("Invitación preparada."); }, 620); });
  const openWhatsapp = document.querySelector("#openWhatsapp"); if (openWhatsapp) openWhatsapp.addEventListener("click", () => window.open(`https://wa.me/?text=${encodeURIComponent(invitationMessage())}`, "_blank", "noopener,noreferrer"));
}
function bindAgreement(nextState = AppState.AGREEMENT_COMPLETE, completeMessage = "Promesa guardada.", acceptedField = "agreementAccepted") {
  cancelAnimationFrame(holdFrame); holdLocked = false; holdProgress = 0; holdStart = 0;
  const root = document.querySelector("#agreementRoot"), button = document.querySelector("#holdButton"), label = document.querySelector("#holdLabel");
  function setProgress(value) { holdProgress = Math.max(0, Math.min(1, value)); button.style.setProperty("--hold-progress", (holdProgress * 100).toFixed(2)); root.style.setProperty("--hold-alpha", holdProgress.toFixed(3)); }
  function complete() { holdLocked = true; onboardingData[acceptedField] = true; setProgress(1); button.classList.add("is-complete"); label.textContent = "✓"; announce(completeMessage); navigator.vibrate?.(30); setTimeout(() => transitionTo(nextState), 820); }
  function tick(now) { if (!holdStart || holdLocked) return; const progress = (now - holdStart) / HOLD_DURATION; setProgress(progress); if (progress >= 1) return complete(); holdFrame = requestAnimationFrame(tick); }
  function start() { if (!holdLocked) { cancelAnimationFrame(holdFrame); holdStart = performance.now() - holdProgress * HOLD_DURATION; holdFrame = requestAnimationFrame(tick); } }
  function cancel() { if (holdLocked) return; cancelAnimationFrame(holdFrame); holdStart = 0; const initial = holdProgress, started = performance.now(); function easeBack(now) { const t = Math.min(1, (now - started) / 320); setProgress(initial * (1 - t)); if (t < 1) requestAnimationFrame(easeBack); } requestAnimationFrame(easeBack); }
  button.addEventListener("pointerdown", event => { button.setPointerCapture?.(event.pointerId); start(); }); ["pointerup", "pointercancel", "pointerleave"].forEach(event => button.addEventListener(event, cancel)); button.addEventListener("keydown", event => { if (event.key === " " || event.key === "Enter") { event.preventDefault(); start(); } }); button.addEventListener("keyup", event => { if (event.key === " " || event.key === "Enter") { event.preventDefault(); cancel(); } });
}
setupReviewMenu();
render();
